default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: cofrinho_development

test:
  <<: *default
  database: cofrinho_test

production:
  primary: &primary_production
    <<: *default
    database: cofrinho_production
    username: cofrinho
    password: <%= ENV["COFRINHO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cofrinho_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cofrinho_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cofrinho_production_cable
    migrations_paths: db/cable_migrate
